# Generated by Django 4.2.6 on 2023-12-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCity', models.CharField(default='', max_length=35, verbose_name='Name')),
                ('district', models.CharField(default='', max_length=20, verbose_name='District')),
                ('population', models.IntegerField(default=0, verbose_name='Population')),
                ('monuments', models.CharField(default='', max_length=45, verbose_name='Monuments')),
                ('climate', models.CharField(default='', max_length=45, verbose_name='Climate')),
                ('countryCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
            ],
            options={
                'verbose_name': 'Nombre City',
                'verbose_name_plural': 'Nombres City',
                'ordering': ['nombreCity'],
                'unique_together': {('nombreCity', 'countryCode')},
            },
        ),
    ]
