# Generated by Django 4.2.6 on 2023-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, verbose_name='Language')),
                ('is_official', models.BooleanField(default=False, verbose_name='IsOfficial')),
                ('percentage', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Percentage')),
                ('alphabet', models.CharField(default='', verbose_name='Alphabet')),
                ('num_speakers', models.IntegerField(default=0, verbose_name='NumSpeakers')),
                ('countries', models.ManyToManyField(to='country.country')),
            ],
            options={
                'verbose_name': 'CountryLanguage',
                'verbose_name_plural': 'CountryLanguages',
            },
        ),
    ]
